import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/components/sessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dmSans = DM_Sans({
subsets: ["latin"],
weight: "800",
variable: "--font-dm-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased ${dmSans.variable} font-sans bg-background text-foreground`}
      >
        <main className="flex-1  bg-gray-50">
          <Provider>{children}</Provider>
        </main>
      </body>
    </html>
  );
}
